SELECT
    C.COMPANY_NAME,
    COUNT(V.ID) AS visitor_count
FROM
    VISITOR AS V
JOIN
	USERS AS U ON V.USER_ID = U.ID
JOIN
    COMPANY AS C ON V.COMPANY_ID = C.ID
GROUP BY
    C.COMPANY_NAME
ORDER BY
    visitor_count DESC
LIMIT 10;
