SELECT
    C.COMPANY_NAME,
    COUNT(E.ID) AS employee_count
FROM
    EMPLOYEE AS E
JOIN
	USERS AS U ON E.USER_ID = U.ID
JOIN
    COMPANY AS C ON E.COMPANY_ID = C.ID
JOIN
	INSIDE_OFFICE AS IO ON IO.USER_ID = U.ID
GROUP BY
    C.COMPANY_NAME
ORDER BY
    employee_count DESC
LIMIT 10;
