--get visitors by company name
SELECT
	C.COMPANY_NAME,
	U.NAME,
	U.SURNAME,
	U.EMAIL, 
	'Visitator' as USER_TYPE
	
FROM
	USERS AS U
	JOIN VISITOR AS V ON V.USER_ID = U.ID
	JOIN COMPANY AS C ON V.COMPANY_ID = C.ID
	JOIN INSIDE_OFFICE AS IO ON IO.USER_ID = U.ID
WHERE
	C.COMPANY_NAME = 'aAafueacHB'