--get user with specific role_id
SELECT DISTINCT
    C.COMPANY_NAME,
    U.NAME,
    U.SURNAME,
    U.EMAIL,
	R.DESCRIPTION
FROM
    COMPANY AS C
LEFT JOIN
    EMPLOYEE AS E ON E.COMPANY_ID = C.ID
LEFT JOIN
    VISITOR AS V ON V.COMPANY_ID = C.ID
LEFT JOIN
    USERS AS U ON U.ID = E.USER_ID OR U.ID = V.USER_ID
LEFT JOIN ROLE AS R ON R.ID = E.ROLE_ID OR R.ID = V.ROLE_ID
WHERE
	R.LEVEL = 2