SELECT DISTINCT
    C.COMPANY_NAME,
    U.NAME,
    U.SURNAME,
    U.EMAIL
FROM
    COMPANY AS C
LEFT JOIN
    EMPLOYEE AS E ON E.COMPANY_ID = C.ID
LEFT JOIN
    VISITOR AS V ON V.COMPANY_ID = C.ID
LEFT JOIN
    USERS AS U ON U.ID = E.USER_ID OR U.ID = V.USER_ID
ORDER BY
    C.COMPANY_NAME, U.NAME, U.SURNAME;



SELECT * FROM USERS;