--get employee with end of permission tomorrow
SELECT
	U.NAME,
	U.SURNAME,
	U.EMAIL,
	P.END_OF_PERMISSION
FROM
	USERS AS U
	JOIN EMPLOYEE AS E ON E.USER_ID = U.ID
	JOIN PERMISSIONS AS P ON E.PERMISSION_ID = P.ID
WHERE
	P.END_OF_PERMISSION > NOW() + INTERVAL '1 DAY';