--get employee inside the office
SELECT
	C.COMPANY_NAME,
	'Visitor' AS USER_TYPE,
	U.NAME,
	U.SURNAME,
	U.EMAIL,
	'YES' AS INSIDE_OFFICE
FROM
	USERS AS U
	JOIN VISITOR AS V ON V.USER_ID = U.ID
	JOIN COMPANY AS C ON V.COMPANY_ID = C.ID
	JOIN INSIDE_OFFICE AS IO ON IO.USER_ID = U.ID
GROUP BY
	C.COMPANY_NAME, U.NAME, U.SURNAME, U.EMAIL
