--get employee/company/role/permission inside the office
SELECT
	U.NAME,
	U.SURNAME,
	U.EMAIL,
	C.COMPANY_NAME,
	R.DESCRIPTION
FROM
	USERS AS U
	JOIN EMPLOYEE AS E ON E.USER_ID = U.ID
	JOIN COMPANY AS C ON E.COMPANY_ID = C.ID
	JOIN ROLE AS R ON E.ROLE_ID = R.ID
	JOIN INSIDE_OFFICE AS IO ON IO.USER_ID = U.ID
