SELECT
	T.DATE,
	T.ENTER_TIME,
	T.EXIT_TIME,
	T.CURRENT_STATE,
	U.NAME,
	U.SURNAME,
	U.EMAIL,
	R.DESCRIPTION,
	C.COMPANY_NAME
FROM
	TRANSACTIONS AS T
	JOIN USERS AS U ON U.ID = T.USER_ID
	JOIN EMPLOYEE AS E ON E.USER_ID = U.ID
	JOIN ROLE AS R ON E.ROLE_ID = R.ID
	JOIN COMPANY AS C ON C.ID = E.COMPANY_ID
WHERE
	C.COMPANY_NAME = 'PsBlaSu3rW'