SELECT
	T.DATE,
	T.ENTER_TIME,
	T.EXIT_TIME,
	T.CURRENT_STATE,
	U.NAME,
	U.SURNAME,
	U.EMAIL,
	R.DESCRIPTION,
	R.LEVEL
FROM
	TRANSACTIONS AS T
	JOIN USERS AS U ON U.ID = T.USER_ID
	JOIN EMPLOYEE AS E ON E.USER_ID = U.ID
	JOIN ROLE AS R ON E.ROLE_ID = R.ID
WHERE
	R.LEVEL > 3 AND R.LEVEL < 7